config/routes.rb
Gds::Application.routes.draw do

   resources :posts 
   match '/home', to: 'posts#index', via: 'get'
   match '/signup', to: 'static_pages#signup', via: 'get'
   match '/sponsors', to: 'static_pages#sponsors', via: 'get'
   match '/showcase', to: 'static_pages#showcase', via: 'get'
   match '/about', to: 'static_pages#about', via: 'get'
   match '/exec', to: 'sessions#create', via: 'post'
   match '/exec', to: 'sessions#new', via: 'get'
   match '/account', to: 'users#edit', via: 'get'
   match '/account', to: 'users#update', via: 'patch'
   match '/signout', to: 'sessions#destroy', via: 'delete'
   match '/newpost', to: 'posts#new', via: 'get'
   match '/newpost', to: 'posts#create', via: 'post'
   match '/tutorials', to: 'static_pages#tutorials', via: 'get'
   root 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
   belongs_to :user

   # Order posts by descending order.
   default_scope -> { order('created_at DESC') }

   # Validations
   validates(:user_id, presence: true)
   validates(:content, presence: true)
   validates(:title, presence: true)
end

app/models/user.rb
class User < ActiveRecord::Base
   has_many :posts
   VALID_NAME_REGEX = /\A[a-zA-z]+\z/i

   # Capitalize names and position before saving to database
   before_save { 
      self.first_name.capitalize!;
      self.last_name.capitalize!;
   }

   before_create :create_remember_token

   # Validation 
   validates(:first_name, { 
      presence: true, 
      format: { with: VALID_NAME_REGEX }, 
      length: { maximum:50 }
   })
   validates(:last_name, { 
      presence: true, 
      format: { with: VALID_NAME_REGEX },
      length: { maximum:50 }
   })
   validates(:position, {
      presence: true,
      uniqueness: { case_sensitive: false }
   })

   validates(:password, {
      presence: true,
      length: { minimum: 8 }
   })

   has_secure_password

   def User.new_remember_token
      SecureRandom.urlsafe_base64
   end

   def User.encrypt(token)
      Digest::SHA1.hexdigest(token.to_s)
   end

   private 
   def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
   include SessionsHelper
   include PostsHelper

   def new
      @post = Post.new
      if (!signed_in?)
         redirect_to root_path
      end
   end

   def create
      @post = Post.new(post_params)
      @post.user_id = current_user.id
      if @post.save 
         redirect_to root_path
      else 
         render 'new'
      end
   end

   def edit 
      if (!signed_in?)
         redirect_to root_path
      end
      @post = Post.find(params[:id])
   end

   def update
      @post = Post.find(params[:id])
      if (@post.update_attributes(post_params))
         redirect_to root_path
      else
         render 'edit'
      end
   end

   def index
      @posts = Post.all
   end

   def destroy
      if (!signed_in?)
         redirect_to root_path
      else
         Post.find(params[:id]).destroy
         redirect_to root_path
      end
   end

   private
   def post_params
      params.require(:post).permit(:title, :content, :content_type)
   end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
   include SessionsHelper
   def new
   end
   def create
      @error=''
      id = params[:session][:position].split
      id.each do |i|
         i.capitalize!
      end
      id = id.join(' ')
      user = User.find_by_position(id)
      if (user && user.authenticate(params[:session][:password]))
         sign_in user
         redirect_to root_path
      else
         if (!user)
            @error = "You don't belong here, do you?"
         elsif (!user.authenticate(params[:session][:password]))
            @error = "Tsk tsk."
         end
         render 'new'
      end

   end
   def destroy
      sign_out
      redirect_to root_path
   end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def signup
  end

  def showcase
  end

  def about
  end

  def constitution
  end

  def contact
  end

  def tutorials
  end

  def sponsors
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   include SessionsHelper

   def new
   end

   def edit
      if (!signed_in?)
         redirect_to root_path
      else
         @user = current_user
      end
   end

   def update
      @user = current_user
      if (@user.update_attributes(user_params))
         @success = true;
         render 'edit'
      else
         render 'edit'
      end
   end

   private
   def user_params
      params.require(:user).permit(:first_name, :last_name, :position, 
                                   :password, :password_confirmation)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper

   # Generates a full title for the page
   def get_title(page_title)
      base_title = "Game Dev Soc UNSW"
      if (page_title.empty?)
         return base_title
      else
         return "#{base_title} | #{page_title}"
      end
   end
   def markdown(text)
      options = [ :hard_wrap, :filter_html, :autolink, :no_intraemphasis, :fenced_code, :gh_blockcode ]
      Redcarpet.new(text, *options).to_html.html_safe
   end

end

app/helpers/posts_helper.rb
module PostsHelper

   def get_author_name(post)
      user = User.find_by(id: post.user_id)
      return "#{user.first_name} #{user.last_name} [#{user.position}]"
   end
end

app/helpers/sessions_helper.rb
module SessionsHelper
   def sign_in(user)
      remember_token = User.new_remember_token
      cookies.permanent[:remember_token] = {
         value: remember_token,
         expires: 1.year.from_now.utc
      }
      user.update_attribute(:remember_token, User.encrypt(remember_token))
      self.current_user = user
   end

   def sign_out
      current_user.update_attribute(:remember_token,
                                    User.encrypt(User.new_remember_token))
      cookies.delete(:remember_token)
      self.current_user = nil
   end

   def current_user=(user)
      @current_user = user
   end

   def current_user
      remember_token = User.encrypt(cookies[:remember_token])
      @current_user ||= User.find_by(remember_token: remember_token)
   end

   def signed_in?
      !current_user.nil?
   end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer", id="footer">
<div class="well">
   <div class="contact">
      <b>
         Contact us <a href="mailto:gamedevsoc.unsw@gmail.com">here</a>
      </b>
      <br>
      <a href="https://www.facebook.com/groups/185233411589007/" target="_blank">
         <button class="btn-tiny btn-facebook", align="right"><i class="fa fa-facebook"></i></button>
      </a> 
   </div>
   <small>
      <b>Maintained by The Cool GDS Exec</b>
   </small>
</div>
</footer>

app/views/layouts/_header.html.erb
<div class="container-fluid">
   <header class="navbar navbar-fixed-top navbar-inverse" id="header">
   <div class="navbar-inner">
      <div class="container">
         <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
         </a>
         <%= link_to "GameDevSoc@UNSW", root_path, id: "logo" %>
         <ul class="nav pull-right">
            <% if signed_in? %>
               <li id="greeting"><i>Hello, <%= "#{current_user.first_name} [#{current_user.position}]" %></i></li>
               <li class="dropdown">
               <a class="dropdown-toggle" id="account" data-toggle="dropdown" href="">
                  Account <span class="caret"></span>
               </a>
               <ul class="dropdown-menu">
                  <li><%= link_to "Create Post", newpost_path %><li>
                  <li><%= link_to "Account Settings", account_path %></li>
                  <li class="divider"></li>
                  <li><%= link_to "Sign Out", signout_path, method: "delete" %></li>
               </ul>
               </li>
            <% end %>
            <div class="nav-collapse">
               <div class="nav">
                  <li><%= link_to "Home",    root_path , id: "navop" %></li>
                  <li><%= link_to "About",    about_path, id: "navop" %></li>
                  <li><%= link_to "Showcase", showcase_path, id: "navop" %></li>
                  <li><%= link_to "Tutorials", tutorials_path, id: "navop" %></li>
                  <li><%= link_to "Sign Up",    signup_path, id: "signup", title: "You know you want to." %></li>
               </div>
            </div>
         </ul>
      </div>
   </div>
   </header>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
   <title><%= get_title(yield(:title)) %></title>
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
   <link rel="shortcut icon" href="<%= asset_path 'logo.png'%>"/>
   <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
   <%= csrf_meta_tags %>
      <!--
      <script type="text/javascript">
         function placeFooter() {

            var docHeight = $(window).height();
            var footerHeight = $('#footer').height();
            var footerTop = $('#footer').position().top + footerHeight;

            if (footerTop < docHeight) {
               $('#footer').css('margin-top',2+ (docHeight - footerTop)+ 'px');
            }
         }
$(document).ready(function() {placeFooter()});

window.addEventListener('resize', placeFooter);
</script> -->
</head>
<body>
   <div class="container-fluid", id="master-section">

      <%= render 'layouts/header' %>
      <div class="container maincontainer">
         <% if yield(:title).to_s == "Home" %>
         <div class="span12 center">
            <div class="hero-unit", id="homeunit">
            <div class="container-fluid">
               <h1>GDS</h1>
               <p>Game Development Society UNSW</p>
</div>
            </div>
         </div>
         <% end %>
         <%= yield %>
      </div>

      <div class="container", id="buffer"></div>

   </div>
   <%= render 'layouts/footer' %>
   <%#= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/posts/edit.html.erb
<% provide(:title, "Edit Post") %>
<div class="well">
   <h1>Edit Post</h1>
   <%= form_for(@post) do |f| %>
      <%= render '/shared/error_messages' %>
      <%= f.label "Title" %>
      <%= f.text_field :title, class: "span7" %>
      <label>Content Type</label>
      <%= f.select :content_type, [['General','general'],['Social','social'],['Workshop','workshop']], {}, { :class => 'form-control'} %>

      <%= f.label "Content" %>
      <%= f.text_area :content, class: "span10" %>
      <br><br>
      <%= f.submit "Save Changes", class: "btn-inverse btn-large btn-primary" %>
   <% end %>
</div>

app/views/posts/index.html.erb
     <% provide(:title, 'Home') %>

     <div class="span9">
       <div class="well">
        <div class="container-fluid">
         <h1>Announcements</h1>
      </div>

      <% @posts.each do |post| %>
      <div id="<%= post.content_type %>">
         <div class="well">
            <div class="container-fluid">
               <div id="edit_options">
                  <b>[<%= post.content_type.to_s.capitalize %>]</b>
               </div>
               <h3><%= post.title %></h3>

               <p><%= markdown(post.content) %></p>
               <br>
               <br>
               Posted on: <%= post.created_at.in_time_zone(Time.zone.name).to_date %>
               <% if post.created_at != post.updated_at %>
               | Updated on: <%= post.updated_at.to_date %>
               <% end %>
               | <i>by <%= get_author_name(post) %></i> 
               <% if signed_in? %>
               <br>
               <%= link_to "Edit", edit_post_path(post) %> 

               <div id="edit_options">
                  <%= link_to "Delete", post, method: :delete,
                  data: { confirm: "Are you sure?" } %>
               </div>
               <% end %>
            </div>
         </div>
      </div> <!--Well-->
      <% end %>
   </div>
</div>
<div class="row">
   <div class="well span2">
        <div align="center">
         <h3>Sponsors</h3>
         <a href="http://www.arc.unsw.edu.au/"><img src="/assets/arc.png"></a>
      </div>
   </div>
</div>
</div>

app/views/posts/new.html.erb
<div class="well">
   <h1>Create Post</h1>
   <%= form_for(@post, url: 'newpost') do |f| %>
      <%= render '/shared/error_messages' %>
      <%= f.label "Title" %>
      <%= f.text_field :title, class: "span7" %>
      <label>Content Type</label>
      <%= f.select :content_type, [['General','general'],['Social','social'],['workshop','workshop']], {}, { :class => 'form-control'} %>

      <%= f.label "Content" %>
      <%= f.text_area :content, class: "span10" %>
      <br><br>
      <%= f.submit "Submit", class: "btn-inverse btn-large btn-primary" %>
   <% end %>
</div>

app/views/shared/_creation_success.html.erb
   <div class="alert alert-success">
      Your changes have been saved.
   </div>

app/views/shared/_error_messages.html.erb
<% @var = @user
   @var ||= @post
   
   if @var.errors.any? 
%>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@var.errors.count, "error") %>.
    </div>
    <ul>
    <% @var.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<div class="well span9 center">
	<h1>About Us</h1>
	<br>
	<p>The Game Development Society at UNSW is a relatively new, 300+ member student run society that aims to facilitate a social and educational 
	environment for students of all disciplines who have an interest in game development.</p>
	<br>
	We currently conduct:
	<br><br>
	<ul>
		<li>
			Workshops for people of varying skill sets and skill levels. Sound design, Art, and Coding are all covered in our workshops. We take care to make sure that even members who have no idea about game development are able to build up enough skills to confidently work on their own projects.
		</li>
		<li>
			Social events such as LAG (Local Area Gaming) Parties, Startup Days and other more laid back gatherings where members can mingle and get to know each other (and hopefully meet future team members!). 
		</li>
	</ul>
	<br>
	So if you aren’t a member yet, what are you waiting for? Head on over to the <a href="<%= signup_path %>">Sign Up</a> page and find out about how you can join!
</div>

app/views/static_pages/constitution.html.erb
<% provide(:title, 'Constitution') %>
<h1>StaticPages#constitution</h1>
<p>Find me in app/views/static_pages/constitution.html.erb</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<div class="span10 well">
   <h1>Announcements</h1>
   <div class="row">

   </div>
</div>

app/views/static_pages/showcase.html.erb
<% provide(:title, 'Showcase') %>
<div class="row">
	<div class="well">
		<h1>Games Showcase</h1>
		<div style="text-align:center">
			This section is currently under construction!
		</div>
	</div>
</div>

app/views/static_pages/signup.html.erb
<% provide(:title, 'Signup') %>
<div class="row">
   <% #Well with Facebook link for low resolutions %>
   <div class="span4 visible-phone">
      <div class="well">
         <div align="center">
            <p>
            <h3>While you're here...</h3>
            <a href="https://www.facebook.com/groups/185233411589007/" target="_blank">
               <button class="btn-large btn-facebook"><i class="fa fa-facebook"></i> | Join us on Facebook!</button>   </p>
            </a>
         </div>
      </div>
   </div>
</div>

<div class="row">
   <% #Well with Facebook link For high resolutions %>
   <div class="span4 hidden-phone", style="float:right;">
      <div class="well side-well">
         <div align="center">
            <p>
            <h3>While you're here...</h3>
            <a href="https://www.facebook.com/groups/185233411589007/" target="_blank">
               <button class="btn-large btn-facebook"><i class="fa fa-facebook"></i> | Join us on Facebook!</button>   </p>
            </a>
         </div>
      </div>
   </div>


   <% #Well with the Signup sheet %>
   <div class="span8">
      <div class="well">
         <h1>How to Sign Up</h1>
         <div class="well instruction-well">
            <ol>
               <li>If you are not a current ARC member, or have not signed up for OrgSync
               click <a href="https://orgsync.com/register/university-of-new-south-wales">here</a>
               (Don't worry, it's free to join!)</li><br>
               <li>After you have created an OrgSync account, log in to OrgSync</li><br>
               <li>Click the search bar at the top of the page and type in "Game Development Society"</li><br>
               <li>Click on the "Game Development Society" organization when it appears in the search results</li><br>
               <li>Click the "Join Club" button the left hand side of the page, and wait for
               one of the Executive Members to approve your request! (We won't say no, promise!)</li><br>
            </ol>
            <p style="text-align:center;"><b><h2>If you have any further questions<br> 
                  <a href="mailto:gamedevsoc.unsw@gmail.com">shoot us an email!</a></h2><b></p>
         </div>
      </div>
   </div>
</div>

app/views/static_pages/sponsors.html.erb
<% provide(:title, 'Sponsors') %>
<div class="well">
   <h1>Our Sponsors</h1>
   <div class="row">
   		
   </div>
</div>

app/views/static_pages/tutorials.html.erb
<% provide(:title, 'Tutorials') %>

<div class="well">
	<h1>Tutorials</h1>
	<h3>Game Theory</h3>
	<h3>Frameworks & Engines</h3>
	<h3>Sound</h3>
	<h3>Art</h3>
	<h3>Helpful Tools</h3>
</div>

app/views/users/edit.html.erb
<div class="well">
   <h1><%= "#{@user.first_name}'s Account" %></h1>
   <div id="login">
      <%= form_for(@user, url: 'account') do |f| %>
         <%= render '/shared/error_messages' %>
         <% if @success %>
            <div class="alert alert-success">
               Your changes have been saved.
            </div>
         <% end %>

         <label>First Name</label>
         <%= f.text_field :first_name %>
         <label>Last Name</label>
         <%= f.text_field :last_name %>
         <label>Password</label>
         <%= f.password_field :password %>
         <label>Password Confirmation</label>
         <%= f.password_field :password_confirmation %>
         <br><br>
         <%= f.submit "Save Changes", class: "btn-inverse btn-large btn-primary" %>
      <%end%>
   </div>
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>